### ISSUE TITLE
[UI] Get visitor location from browser

### ISSUE THREAD

**Issue by mageo** [stayhomech/stayhomech#12]
Add a button to fetch location from browser.

**Comment by pavax** [comment]
1. use the Browser Geo-Location API: https://developer.mozilla.org/de/docs/Web/WebAPI/verwenden_von_geolocation
2. use a reverse-geocode API to get the postal code: 
  https://developers.arcgis.com/rest/geocode/api-reference/geocoding-reverse-geocode.htm
 Example:
 http://geocode.arcgis.com/arcgis/rest/services/World/GeocodeServer/reverseGeocode?f=pjson&langCode=EN&location=7.16197,46.80647
