### ISSUE TITLE
Create REST API to create/update/delete requests

### ISSUE THREAD

**Issue by mageo** [stayhomech/stayhomech#13]
Create REST API to create/update/delete requests.

This will be used by external crawlers to interact directly with the DB.

Access will be restricted using an API key.

**Comment by mageo** [comment]
Each successful creation request performed on the API must generate an unique key used to make change to the created request and associated business as well as being able to remove a request and associated business.

**Comment by mageo** [comment]
The request object in database must provide a raw field to store JSON information usefull to the crawler but not used by stayhome itself.

**Comment by mageo** [comment]
Add a TTL field to automate removal of automated additions.

**Comment by mageo** [comment]
Add a source field in order to identify the source of the request. (webfom, api, api datasource, ...)

**Comment by pavax** [comment]
@mageo Could you provide us some basic examples using curl

1. Fetch a Request by the externald
2. Update a Request
3. Create a Request

**Comment by mageo** [comment]
Regarding point 1 of your request, how do you want to search ? The "external id" field is named source_uuid and is a text field (255 chars). I can basically implement anything.

Would for example a REGEXP be sufficient ? Something like :

api.stayhome.ch/requests/?source_uuid=^agentXXX_.*

Or a simple "starts with" ?

api.stayhome.ch/requests/?source_uuid=agentXXX_

Or anything else ?

**Comment by pavax** [comment]
It would be sufficient to have an "exact" match that returns either:
* 404 Not found (or anything similiar)
* a single entry

**Comment by mageo** [comment]
Ok, that's the easiest way :-)
