### ISSUE TITLE
More meaningful errors in the backend

### ISSUE THREAD

**Issue by UncleSamSwiss** [stayhomech/stayhomech#132]
If when working in the backend, I get an error 500, it would be good to have some more information. I'm sure this is configurable in Django.

Of course only for the backend, not the frontend.

**Comment by mageo** [comment]
Not a definitive solution but you can see all errors on sentry.io : 

https://sentry.io/organizations/stayhomech/issues/?project=4999825

Login with GitHub account. Let me know if you cannot access.
