### ISSUE TITLE
Tag cloud with categories in the result list

### ISSUE THREAD

**Issue by UncleSamSwiss** [stayhomech/stayhomech#133]
It would be great to have a weighted tag cloud next to the results (in the left area) to quickly filter for categories.

Example:
![image](https://user-images.githubusercontent.com/7595126/78158207-3fc82900-7441-11ea-9e0d-346de1875f1b.png)

**Comment by mageo** [comment]
As the categories are organized as a tree, I don't think this way of displaying the information is clear enough.
