### ISSUE TITLE
Requests Processing Data cleared on Validation Error

### ISSUE THREAD

**Issue by pavax** [stayhomech/stayhomech#139]
Every time there is a validation error during the processing of a Request, the data that I filled out is cleared again.

Example Validation Error that cleared the form:
```
Einige Validierungsfehler sind aufgetreten:
No main category selected and no new category provided.
```

**Comment by pavax** [comment]
I guess this one has been fixed, right @mageo

**Comment by mageo** [comment]
Not completely but I will move it to enhancements.
