### ISSUE TITLE
[Filtering]: Sort Sub-Categories alphabetically

### ISSUE THREAD

**Issue by pavax** [stayhomech/stayhomech#190]
Let's try to sort the Sub-Categories alphabetically to make it more easy to find find a particular category  of interest....

![image](https://user-images.githubusercontent.com/5336841/78674493-fa45a900-78e3-11ea-84f8-b2429c0dbdad.png)

**Comment by mageo** [comment]
That should already be the case :(

Il will rebuild the category tree tonight when I perform the other maintenance.

**Comment by mageo** [comment]
Ah damn... found maybe why... the sorting of categories is performed based on the english translation. I'll create a workaround.
