### ISSUE TITLE
Report a Business-Entry

### ISSUE THREAD

**Issue by pavax** [stayhomech/stayhomech#61]
We need a Link/Button on every entry to report an business-entry. A report could be, that there is a problem with the data. For example: Link is not working or the delivery proximeter is wrong.

**Comment by mageo** [comment]
Absolutely, This will be added to the current batch of UI enhancements I will work on asap :-D

**Comment by mageo** [comment]
A "quick and dirty" solution has been applied but I can and will do better on the next UI release.
