### ISSUE TITLE
Integration: DerBund contact-field constraint errors (max-size)

### ISSUE THREAD

**Issue by pavax** [stayhomech/stayhomech#72]
**Problem:**  For some entries (~27 - 26.03.2020-16:00) the contact field exceeds to limit of 255 chars

**Example:**
Id: 8.4001_47.4043
Provider: DerBund
Example: https://sentry.io/share/issue/216ad8dac9fd49f596ed86bf97daa336/

**Possible Solutions:** 
* Increase the Limit on the Backend (@mageo ) 
* Logic in the Integrator App to cut the text or use the field description instead if > 255
* Logic in the Sync-Service to cut the text or use the field description instead if > 255

@UncleSamSwiss  what do you think?

**Comment by mageo** [comment]
I upgraded to field to a Text type, no more length limitation. Not in master yet.
