### ISSUE TITLE
Getting started for local environment

### ISSUE THREAD

**Issue by pavax** [stayhomech/stayhomech#9]
Suggestions:
* Provide a Readme
* Provide a local docker-compose

**Comment by mageo** [comment]
Damn, I must work with PR now, sorry ! I updated the README and made a few changes to the code to have a docker-compose-dev file to run the project.

Please let me know if it is clear enough and I will close the issue.

**Comment by lugipfupf** [comment]
I've set up my env using Docker and your docker-compose.yml, works like a charm, so didn't even try option 1 ;-)

**Comment by mageo** [comment]
This is solved I think.
